import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-0 p-0">
        {/* We use flex to place them side-by-side */}
        <div style={{ display: "flex", width: "100%" }}>
          {/* Sidebar takes fixed width */}
          <div style={{ width: "250px", flexShrink: 0 }}>
            <Sidebar />
          </div>

          {/* Main content takes all remaining space */}
          <main style={{ flex: 1, padding: "20px" }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
